Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-07, with the labels that each got.

#87 PLNSRVCE-448: clean up unneeded operator rbac perms; fix mvn-goals on openshift
  deploy/base/maven-v0.2.yaml
  deploy/base/run-maven-component-build-v0.1.yaml
  deploy/operator/base/rbac.yaml
Labels: approved, lgtm

#88 PLNSRVCE-452: create dockerfile to build cache image in openshift ci
  .dockerignore
  Dockerfile.cache-in-ci
Labels: approved

#89 PLNSRVCE-452: create dockerfile to build sidecar,dep analyzer, and req processor images in openshift ci
  Dockerfile.analyzer-in-ci
  Dockerfile.reqprocessor-in-ci
  Dockerfile.sidecar-in-ci
Labels: approved

#90 PLNSRVCE-452: update ci script/README with CI overrides for java based images
  .ci/README.md
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved, do-not-merge/hold

#92 PLNSRVCE-452: get run sample build running on openshift using jvm-build-service deployed by appstudio
  deploy/base/maven-v0.2.yaml
  deploy/base/run-maven-component-build-v0.1.yaml
  deploy/cache/base/deployment.yaml
  deploy/cache/base/service.yaml
  deploy/development.sh
  deploy/namespace.yaml
  deploy/operator/base/deployment.yaml
  deploy/operator/base/sa.yaml
  deploy/overlays/dev-template/localstack.yaml
  hack/examples/openshift-specific-rbac.yaml
  hack/examples/run-build-discovery.sh
  hack/examples/run-quarkus-security-build.sh
  hack/examples/run-sample-pipeline.sh
  hack/examples/run-service-registry.sh
  hack/examples/run-service-registry.yaml
  hack/examples/run.yaml
Labels: approved, lgtm

#96 PLNSRVCE-454: Move to pipelines for artifact discovery
  deploy/base/kustomization.yaml
  deploy/base/lookup-artifact-location-v0.1.yaml
  deploy/base/maven-v0.2.yaml
  deploy/base/rbac.yaml
  deploy/base/run-gradle-component-build-v0.1.yaml
  deploy/base/run-maven-component-build-v0.1.yaml
  deploy/cache/overlays/dev-template/kustomization.yaml
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/development.sh
  deploy/operator/base/rbac.yaml
  deploy/overlays/dev-template/kustomization.yaml
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/BuildRecipe.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildStatus.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/artifactbuild/controller.go
  pkg/reconciler/dependencybuild/controller.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/task_run_controller_test.go
Labels: approved, lgtm

#98 PLNSRVCE-452: add anyuid to cache deployment to get past startup errors
  deploy/cache/base/deployment.yaml
  deploy/cache/base/kustomization.yaml
  deploy/cache/base/rbac.yaml
  deploy/cache/base/sa.yaml
Labels: approved, lgtm

#93 Adding a container registry storage option
  java-components/cache/pom.xml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/LocalCache.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryType.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/ShaUtil.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/ociregistry/OCIRegistryRepositoryClient.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/ContainerRegistryTestResourceManager.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/S3TestResourceManager.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/ContainerRegistryStorageTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/S3ArtifactStorageTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/test/util/HashUtil.java
Labels: lgtm, ok-to-test

#102 PLNSRVCE-446: switch to tekton object based pruning in the operator
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved, lgtm

#104 use git-clone task defined in build-definitions
  deploy/base/kustomization.yaml
Labels: approved, lgtm

#113 make sure taskrun CRD exists before we init controller-runtime to watch it
  deploy/operator/base/rbac.yaml
  pkg/controller/controller.go
Labels: approved, do-not-merge/hold

#116 disable pruning of taskruns in e2e's to help potential debug
  .ci/common-ci-settings-and-functions.sh
Labels: approved

#117 keep in repo e2e test namespace around for analysis for time being
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
Labels: approved, lgtm

#120 Minor improvements
  deploy/cache/base/deployment.yaml
  java-components/adhoc-analyser-tool/src/main/java/com/redhat/hacbs/analyser/kube/ResetDependencyBuildsCommand.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/BuildRecipe.java
Labels: approved, lgtm

#119 Display the sidecar logs if a task fails
  deploy/base/run-maven-component-build-v0.1.yaml
Labels: lgtm

#118 PLNSRVCE-455: convert maven/gradle cluster tasks into hard coded task specs
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/operator/overlays/dev-template/operator-images.yaml
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved, lgtm, do-not-merge/hold

#124 Run generate.sh to update yamls
  .tekton/hacbs-jdk11-builder-pull-request.yaml
  .tekton/hacbs-jdk11-builder-push.yaml
  .tekton/hacbs-jdk17-builder-pull-request.yaml
  .tekton/hacbs-jdk17-builder-push.yaml
  .tekton/hacbs-jdk8-builder-pull-request.yaml
  .tekton/hacbs-jdk8-builder-push.yaml
  builder-images/generate.sh
  builder-images/pull-request.yaml
Labels: lgtm

#126 Revert "switch to tekton object based pruning in the operator"
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: lgtm

#127 PLNSRVCE-452: only disable pruning for in repo e2e's
  .ci/common-ci-settings-and-functions.sh
  Makefile
Labels: approved

#129 PLNSRVCE-452: switch back to TR pruning, remove TR related tests; test improvements; some code fixes
  Makefile
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
Labels: approved

#130 wait for pipeline SA to get created in new project before testing in earnest
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
Labels: approved, lgtm

#133 PLNSRVCE-452: switch to less expensive test repo
  hack/examples/run-e2e-shaded-app.sh
  hack/examples/run-e2e-shaded-app.yaml
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
Labels: approved

#131 PLNSRVCE-454 move to pipelines
  deploy/base/kustomization.yaml
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/operator/base/rbac.yaml
  hack/examples/run.yaml
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/BuildRecipe.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildStatus.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/artifactbuild/controller.go
  pkg/reconciler/dependencybuild/controller.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/task_run_controller_test.go
Labels: approved, lgtm

#132 PLNSRVCE-528 fix issue with contaminated builds
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/DeployResource.java
  java-components/sidecar/src/main/resources/application.properties
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  test/e2e/task_run_controller_test.go
Labels: approved

#134 PLNSRVCE-449: add kcp api files; various golang source checks
  .github/workflows/go-ci.yaml
  Makefile
  config/kcp/apiexport_jvmbuildservice.yaml
  config/kcp/apiresourceschema_jvmbuildservice.yaml
  config/kcp/kustomization.yaml
  go.mod
  hack/generate-kcp-api.sh
  hack/install-controller-gen.sh
Labels: approved, lgtm

#135 revert run.yaml back to 'code-with-quarkus'
  Makefile
  hack/examples/run.yaml
  openshift-with-appstudio-test/e2e/client.go
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
Labels: approved

#147 abort override-tekton-bundle.sh if JVM_BUILD_SERVICE_PR_SHA not set
  .ci/README.md
  .ci/override-tekton-bundle.sh
Labels: approved
