Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-08, with the labels that each got.

#148 another attempt at checking for whether JVM_BUILD_SERVICE_PR_SHA is set in override tekton script
  .ci/override-tekton-bundle.sh
Labels: approved

#128 Added Container Registry storage
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/ContainerRegistryTestResourceManager.java
  java-components/sidecar/pom.xml
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/DeployResource.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/Deployer.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/DeployerUtil.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/Gav.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ImageData.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/s3/S3Deployer.java
  java-components/sidecar/src/test/java/com/redhat/hacbs/sidecar/resources/deploy/DeployResourceTest.java
  java-components/sidecar/src/test/java/com/redhat/hacbs/sidecar/test/resources/ContainerRegistryDeployerTest.java
  java-components/sidecar/src/test/java/com/redhat/hacbs/sidecar/test/resources/ContainerRegistryDeployerTestResource.java
Labels: ok-to-test

#137 PLNSRVCE-532: Add new fields to the components in the generated SBOM file
  java-components/dependency-analyser/src/main/java/com/redhat/hacbs/container/analyser/AnalyserBase.java
Labels: approved, lgtm

#151 need override bundles call back for CI
  .ci/common-ci-settings-and-functions.sh
Labels: approved

#150 PLNSRVCE-533: fix: use hacbs bundle, override sidecar image
  .ci/override-tekton-bundle.sh
Labels: approved, lgtm

#154 PLNSRVCE-534: have sidecar image pull policy conform with production grade k8s conventions
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved, lgtm

#157 PLNSRVCE-534: add openshift CI periodic test for building service registry
  Makefile
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#160 PLNSRVCE-534: bypass image overrides in ci scripts for periodics and rehearsals
  .ci/common-ci-settings-and-functions.sh
Labels: approved, lgtm

#163 hack to get periodic_test.go to compile in openshift CI while we work Pavel's PR
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#159 Add .editorconfig
  .editorconfig
Labels: lgtm

#164 PLNSRVCE-534: abort override bundle for periodic but do not exit CI setup
  .ci/override-tekton-bundle.sh
Labels: approved

#168 PLNSRVCE-534: rebase periodic to create test namespace config map for artifact cache
  openshift-with-appstudio-test/e2e/const.go
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/types.go
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#170 Don't include rebuilt as a default policy
  java-components/cache/src/main/resources/application.properties
Labels: approved, lgtm

#165 Add service account for local testing
  deploy/base/config.yaml
  deploy/base/kustomization.yaml
  deploy/base/pipeline.yaml
Labels: approved, lgtm

#173 PLNSRVCE-534: more periodic tuning based on openshift/release rehearsals
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#174 PLNSRVCE-534: do not claim periodic success when counts 0 or super low
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#171 Fix PipelineRun pruning
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: do-not-merge/hold

#175 correct periodic db count check
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#178 Add packages (cmake, diffutils, file) required by netty-tcnative
  builder-images/Dockerfile.template
  builder-images/hacbs-jdk11-builder/Dockerfile
  builder-images/hacbs-jdk17-builder/Dockerfile
  builder-images/hacbs-jdk8-builder/Dockerfile
Labels: lgtm

#176 Add gradle based test
  hack/examples/run-e2e-shaded-app.yaml
Labels: approved, lgtm

#179 fix: set recreate strategy for cache deployment
  pkg/reconciler/configmap/configmap.go
Labels: approved

#162 PNC fallback
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/ociregistry/OCIRegistryRepositoryClient.java
  java-components/sidecar/pom.xml
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/GavRelocationConfig.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/HashUtil.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/MavenProxyResource.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/relocation/Gav.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/relocation/RelocationCreator.java
  java-components/sidecar/src/main/resources/application.properties
  java-components/sidecar/src/test/java/com/redhat/hacbs/sidecar/test/resources/FallbackTest.java
Labels: lgtm, ok-to-test

#182 Improve check for Gradle home directory
  deploy/base/gradle-v0.1.yaml
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: lgtm

#181 PLNSRVCE-553: Add Gradle Manipulator to builder images
  builder-images/Dockerfile.template
  builder-images/build-local.sh
  builder-images/generate.sh
  builder-images/hacbs-jdk11-builder/Dockerfile
  builder-images/hacbs-jdk17-builder/Dockerfile
  builder-images/hacbs-jdk8-builder/Dockerfile
Labels: lgtm

#189 PLNSRVCE-587: Add ninja-build package required by netty-tcnative
  builder-images/Dockerfile.template
  builder-images/hacbs-jdk11-builder/Dockerfile
  builder-images/hacbs-jdk17-builder/Dockerfile
  builder-images/hacbs-jdk8-builder/Dockerfile
Labels: lgtm

#190 PLNSRVCE-588: Add eclipselink maven repository for commonj.sdo:common…
  deploy/base/config.yaml
  deploy/cache/base/deployment.yaml
  openshift-with-appstudio-test/e2e/util.go
Labels: lgtm

#193 Allow sidecar to read configmap
  deploy/base/rbac.yaml
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: lgtm

#196 PLNSRVCE-585: add focused debug for service registry periodic to accelerate failures to target
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#161 PLNSRVCE-533: test: update in-repo tests, use component pipeline
  .ci/common-ci-settings-and-functions.sh
  .ci/override-tekton-bundle.sh
  openshift-with-appstudio-test/e2e/README.md
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
Labels: approved

#191 Added a way to prepend the SHA tags for container registry
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/ociregistry/OCIRegistryRepositoryClient.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ContainerRegistryDeployer.java
Labels: lgtm

#199 add test to make sure subsequent builds use rebuilt dependencies from initial build
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#197 fix string format error; fix for missing pods in periodic debug of failed dependencybuilds
  Makefile
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/util.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved

#198 handle bucket creation timing window
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/s3/S3Deployer.java
Labels: approved, lgtm

#200 feat: added codecov, golangci-lint, security scan
  .codecov.yml
  .github/workflows/build.yml
  .github/workflows/codecov-main.yaml
  .github/workflows/go-ci.yaml
  .gitignore
  Makefile
  openshift-with-appstudio-test/e2e/client.go
  openshift-with-appstudio-test/e2e/const.go
  openshift-with-appstudio-test/e2e/main_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/types.go
  openshift-with-appstudio-test/e2e/util.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/configmap/configmap.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  readme.adoc
Labels: approved

#203 PLNSRVCE-654: Allow checking out commits in addition to branches
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
Labels: lgtm
