Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-10, with the labels that each got.

#270 PLNSRVCE-658: fix deployment get/create, failed attempt to fix service get/create
  deploy/base/config.yaml
  deploy/kcp/apibinding_jvmbuildservice.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/overlays/dev-template/config.yaml
  hack/generate-kcp-api.sh
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/report.html
  openshift-with-appstudio-test/e2e/util.go
  openshift-with-appstudio-test/main/generatereport.go
  pkg/apis/jvmbuildservice/v1alpha1/userconfig_types.go
  pkg/controller/controller.go
  pkg/reconciler/userconfig/userconfig.go
  pkg/reconciler/userconfig/userconfig_test.go
Labels: approved

#282 PLNSRVCE-658: misc kcp clean up to help infra-deployments
  cmd/controller/main.go
  deploy/kcp/apibinding_jvmbuildservice.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/overlays/ci-template/config.yaml
  deploy/overlays/ci-template/kustomization.yaml
  deploy/overlays/ci-template/secret.yaml
  deploy/user-namespace-only.sh
  hack/generate-kcp-api.sh
Labels: approved, lgtm

#287 Update infra-deployment: new path and new script for APIExport update
  .tekton/controller-push.yaml
Labels: lgtm

#290 More periodic upds
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#289 PLNSRVCE-658: add k8s resource quota as an option (kcp env)
  deploy/base/config.yaml
  deploy/crds/base/jvmbuildservice.io_systemconfigs.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  deploy/operator/base/rbac.yaml
  deploy/operator/config/system-config.yaml
  pkg/apis/jvmbuildservice/v1alpha1/systemconfig_types.go
  pkg/controller/controller.go
  pkg/reconciler/k8sresourcequota/controller.go
  pkg/reconciler/k8sresourcequota/k8sresourcequota.go
  pkg/reconciler/systemconfig/systemconfig.go
  pkg/reconciler/tektonwrapper/tektonwrapper.go
  pkg/reconciler/tektonwrapper/tektonwrapper_test.go
Labels: approved

#301 remove defunct analyzer image refs from ci init script
  .ci/common-ci-settings-and-functions.sh
Labels: approved

#302 use vanilla appstudio bundle for PaC builds
  .tekton/build-request-processor-pull-request.yaml
  .tekton/build-request-processor-push.yaml
  .tekton/cache-pull-request.yaml
  .tekton/cache-push.yaml
Labels: approved, lgtm

#292 Add preprocessor tasks
  deploy/base/config.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/EntryPoint.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/AbstractPreprocessor.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/gradle/GradlePrepareCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/maven/MavenPrepareCommand.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/build/AbstractPreprocessorTestCase.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/build/GradlePreprocessorTestCase.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/build/MavenPreprocessorTestCase.java
  java-components/build-request-processor/src/test/resources/gradlebuilds/jsonp/build.gradle
  java-components/build-request-processor/src/test/resources/gradlebuilds/jsonp/build.gradle.expected
  java-components/build-request-processor/src/test/resources/mavenbuilds/narayana/pom.xml
  java-components/build-request-processor/src/test/resources/mavenbuilds/narayana/pom.xml.expected
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryCache.java
  openshift-with-appstudio-test/e2e/util.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: do-not-merge/hold

#296 Make sure artifact states are updated on rebuild
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
Labels: approved, lgtm

#281 PNC fallback fix for cache, added IT test for relocation
  deploy/crds/base/jvmbuildservice.io_userconfigs.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  deploy/overlays/dev-template/config.yaml
  hack/examples/run-e2e-shaded-app.yaml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/resources/application.properties
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/S3TestResourceManager.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/ContainerRegistryStorageTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/RelocationResourceTestCase.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/S3ArtifactStorageTest.java
  openshift-with-appstudio-test/e2e/util.go
  pkg/apis/jvmbuildservice/v1alpha1/userconfig_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/userconfig/userconfig.go
Labels: lgtm

#308 PLNSRVCE-762: avoid quota watches with kcp for now
  pkg/controller/controller.go
  pkg/reconciler/systemconfig/controller.go
  pkg/reconciler/systemconfig/systemconfig.go
  pkg/reconciler/tektonwrapper/controller.go
  pkg/reconciler/tektonwrapper/tektonwrapper.go
  test/e2e/suite_test.go
Labels: approved, lgtm

#307 Don't mark AB as succeeded if it is not deployed
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
Labels: approved, lgtm

#313 PLNSRVCE-762: build image names in KCP via IMAGE_* env vars
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/userconfig/userconfig_test.go
  pkg/reconciler/util/util.go
  test/e2e/task_run_controller_test.go
Labels: approved, lgtm

#320 PLNSRVCE-762: get shaded e2e working on KCP
  cmd/controller/main.go
  deploy/kcp/apibinding_jvmbuildservice.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  hack/generate-kcp-api.sh
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/rebuiltartifact/controller.go
  pkg/reconciler/rebuiltartifact/rebuiltartifact.go
  pkg/reconciler/rebuiltartifact/rebuiltartifact_test.go
  pkg/reconciler/systemconfig/systemconfig.go
  pkg/reconciler/tektonwrapper/controller.go
  pkg/reconciler/userconfig/controller.go
  pkg/reconciler/userconfig/userconfig.go
  pkg/reconciler/userconfig/userconfig_test.go
  pkg/reconciler/util/util.go
  test/e2e/suite_test.go
  test/e2e/task_run_controller_test.go
Labels: approved, lgtm

#322 Don't count inlined methods as contaminants
  java-components/classfile-tracker/src/main/java/com/redhat/hacbs/classfile/tracker/ClassFileTracker.java
Labels: approved, lgtm

#323 PLNSRVCE-762: activate ResourceQuota watch on KCP; rm remaining deployment related claims on KCP
  deploy/kcp/apibinding_jvmbuildservice.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  hack/generate-kcp-api.sh
  pkg/reconciler/systemconfig/systemconfig.go
  pkg/reconciler/tektonwrapper/tektonwrapper.go
Labels: approved, lgtm

#321 PLNSRVCE-695 Don't create ArtifactBuild's if not enabled
  hack/examples/pipeline.yaml
  hack/examples/run-quarkus.sh
  hack/examples/run-quarkus.yaml
  hack/examples/run-wildfly.sh
  hack/examples/run-wildfly.yaml
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/task_run_controller_test.go
Labels: approved

#331 Build with lowest JDK first
  deploy/operator/config/system-config.yaml
Labels: approved, lgtm

#330 PLNSRVCE-762: update pac infra-deployment update to use regex for commit update
  .tekton/controller-push.yaml
Labels: approved, lgtm

#332 prune kcp/compute cache rbac
  deploy/kcp-hacbs-workspace-compute-cluster-rbac/templates/rbac.yaml
  deploy/kcp-hacbs-workspace-init/templates/rbac.yaml
  readme.adoc
Labels: approved

#335 PLNSRVCE-762: update chart/template/instructions to test both developer flow and images at quay.io/redhat-appstudio
  deploy/init-hacbs-user-workspace.sh
  deploy/kcp-hacbs-workspace-init/templates/deployment.yaml
  deploy/kcp-hacbs-workspace-init/templates/maven-task.yaml
  deploy/kcp-hacbs-workspace-init/templates/userconfig.yaml
  deploy/kcp-hacbs-workspace-init/values.yaml
  readme.adoc
Labels: approved

#341 more attempts to make the KCP readme understandable for others
  readme.adoc
Labels: approved

#337 Improve org analysis
  java-components/adhoc-analyser-tool/src/main/java/com/redhat/hacbs/analyser/repoutils/AnalyseGithubOrgCommand.java
Labels: lgtm

#342 save more controller-push pac jobs to help debug flakes
  .tekton/controller-push.yaml
Labels: approved

#340 Detect Java version from Gradle build files
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtils.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtilsTest.java
Labels: lgtm

#345 fix: env var typo
  deploy/init-hacbs-user-workspace-sa-rbac.sh
Labels: approved, lgtm

#344 Allow execution to continue on pre-processor error
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/maven/MavenPrepareCommand.java
Labels: lgtm

#347 fix kubeconfig env var in helm rbac script
  deploy/init-hacbs-user-workspace-sa-rbac.sh
Labels: approved

#353 Ignore PipelineRuns synced from KCP
  pkg/controller/controller.go
Labels: approved, lgtm

#355 Add tmp chains fix
  cmd/deletechainsfinalizer/main.go
Labels: approved, lgtm
