Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-11, with the labels that each got.

#356 untested ingress placeholder for ingressed based access to the artfact cache
  deploy/kcp-hacbs-workspace-init/templates/ingress.yaml
  deploy/kcp-hacbs-workspace-init/templates/service.yaml
Labels: approved, lgtm

#358 Minor cache fix
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryCache.java
Labels: lgtm

#359 fix(minikube): make minikube working again :)
  deploy/minikube-development.sh
Labels: approved, lgtm

#360 Use e2e test for staging build
  hack/examples/staging-build.yaml
Labels: approved, lgtm

#374 tekton-ci: return to pre-kcp format
  .tekton/controller-push.yaml
Labels: approved, lgtm

#382 switch from tektonwrappers to pending pipelineruns for throttling
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/tektonwrapper/controller.go
  pkg/reconciler/tektonwrapper/pending.go
  pkg/reconciler/tektonwrapper/pending_test.go
  pkg/reconciler/tektonwrapper/tektonwrapper.go
  pkg/reconciler/tektonwrapper/util.go
  test/e2e/suite_test.go
Labels: approved, lgtm

#384 remove tektonwrapper from api/code/yaml
  deploy/crds/base/jvmbuildservice.io_tektonwrappers.yaml
  deploy/crds/base/kustomization.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  deploy/operator/base/rbac.yaml
  pkg/apis/jvmbuildservice/v1alpha1/register.go
  pkg/apis/jvmbuildservice/v1alpha1/tektonwrapper_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_tektonwrapper.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/tektonwrapper.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/interface.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/tektonwrapper.go
  pkg/client/listers/jvmbuildservice/v1alpha1/expansion_generated.go
  pkg/client/listers/jvmbuildservice/v1alpha1/tektonwrapper.go
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/clusterresourcequota/controller.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/pendingpipelinerun/controller.go
  pkg/reconciler/pendingpipelinerun/pending.go
  pkg/reconciler/pendingpipelinerun/pending_test.go
  pkg/reconciler/pendingpipelinerun/util.go
  pkg/reconciler/tektonwrapper/controller.go
  pkg/reconciler/tektonwrapper/pending_test.go
  pkg/reconciler/tektonwrapper/tektonwrapper.go
  pkg/reconciler/tektonwrapper/util.go
  test/e2e/suite_test.go
Labels: approved
