Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-06, with the labels that each got.

#69 PLNSRVCE-363: preliminary e2e-test integration (will get verification once openshift/release is updated to consume)
  .ci/README.md
  .ci/oci-e2e-jvm-build-service.sh
  .ci/openshift-ci/Dockerfile
Labels: approved

#70 PLNSRVCE-363: differentiate bld-svc vs. jvm-bld-svc env vars for infra-deployments
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved

#71 fix names of exported env vars
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved

#72 e2e debug
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved

#73 Revert "Merge pull request #72 from gabemontero/more-e2e-fixes"
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved

#74 PLNSRVCE-363: new e2e readme corrections
  .ci/README.md
Labels: approved, lgtm

#75 PLNSRVCE-363: create dir that is required for openshift/release CI image build
  java-components/cache/src/main/docker/Dockerfile.all-in-one
Labels: approved

#78 Fix typo in .ci/oci-e2e-jvm-build-service.sh
  .ci/oci-e2e-jvm-build-service.sh
Labels: lgtm

#60 Initial discovery prototype
  deploy/base/lookup-artifact-location-v0.1.yaml
  deploy/base/run-maven-component-build-v0.1.yaml
  deploy/crds/base/jvmbuildservice.io_artifactbuilds.yaml
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/operator/base/rbac.yaml
  deploy/overlays/dev-template/kustomization.yaml
  hack/examples/quarkus-security-abr.yaml
  java-components/adhoc-analyser-tool/src/main/java/com/redhat/hacbs/analyser/artifactanalysis/AnalyseRepositoriesCommand.java
  java-components/adhoc-analyser-tool/src/main/java/com/redhat/hacbs/analyser/kube/ResetArtifactBuildsCommand.java
  java-components/adhoc-analyser-tool/src/main/java/com/redhat/hacbs/analyser/kube/ResetDependencyBuildsCommand.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/BuildRecipe.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfoManager.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/BuildInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/LookupBuildRecipesCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/VersionRange.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/ArtifactBuildStatus.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/BuildRecipe.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildSpec.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildStatus.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/DeployResource.java
  pkg/apis/jvmbuildservice/v1alpha1/artifactbuildrequest_types.go
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/artifactbuild/artifactbuildrequest.go
  pkg/reconciler/artifactbuild/artifactbuildrequest_test.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/task_run_controller_test.go
Labels: lgtm

#83 maven-component-build: reduce number of steps, set limits
  deploy/base/run-maven-component-build-v0.1.yaml
Labels: lgtm

#84 fix: openshift-ci script for running tests
  .ci/oci-e2e-jvm-build-service.sh
Labels: lgtm
