Repository redhat-appstudio/jvm-build-service, pull requests merged in 2022-09, with the labels that each got.

#210 Fix Gradle version selection
  deploy/base/gradle-v0.1.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtils.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtilsTest.java
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: lgtm

#207 fix: golint, gosec
  .github/workflows/go-ci.yaml
  openshift-with-appstudio-test/e2e/client.go
  openshift-with-appstudio-test/e2e/const.go
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/main_test.go
  openshift-with-appstudio-test/e2e/types.go
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#217 Run Maven in non-interactive (batch) mode
  deploy/base/maven-v0.2.yaml
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: lgtm

#215 shift dev flow toward CI flow (possible prep for kcp disruption)
  Makefile
  deploy/cache/overlays/dev-template/kustomization.yaml
  deploy/development.sh
  deploy/install-openshift-pipelines.sh
  deploy/openshift-pipelines-subscription.yaml
  deploy/openshit-ci.sh
  deploy/operator/overlays/dev-template/kustomization.yaml
  deploy/operator/overlays/dev-template/operator-images.yaml
  deploy/overlays/dev-template/config.yaml
  deploy/overlays/dev-template/kustomization.yaml
  deploy/overlays/dev-template/system-config.yaml
  deploy/patch-yaml.sh
  docs/development/samples.adoc
Labels: approved, lgtm

#225 match timeout used in e2e-tests for jvm-build-service-e2e
  .ci/oci-e2e-jvm-build-service.sh
Labels: approved, lgtm

#218 Attempt to improve sidecar connection reliability
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/MavenProxyResource.java
  java-components/sidecar/src/main/resources/application.properties
  pkg/reconciler/configmap/configmap.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved, lgtm

#222 Use Quarkus 2.12.0.Final
  java-components/pom.xml
Labels: approved, lgtm

#219 Change samples to use taskRunSpecs
  hack/examples/run-e2e-shaded-app.yaml
  hack/examples/run-service-registry.yaml
  hack/examples/run.yaml
Labels: approved, lgtm

#228 Improve error message
  Makefile
Labels: lgtm

#234 fix: test with pre-kcp branch
  .ci/common-ci-settings-and-functions.sh
  .ci/override-tekton-bundle.sh
Labels: approved

#237 Remove pipelines from makefile
  Makefile
Labels: approved, lgtm

#243 fix file name
  deploy/openshift-ci.sh
Labels: approved

#233 PLNSRVCE-669 Allow the artifact cache to be configured
  pkg/reconciler/configmap/configmap.go
  pkg/reconciler/configmap/configmap_test.go
Labels: approved

#245 tweaks/workarounds to get dev flow working on CI
  deploy/base-development.sh
  deploy/base/config.yaml
  deploy/openshift-ci.sh
  deploy/overlays/dev-template/config.yaml
  deploy/overlays/dev-template/secret.yaml
  deploy/patch-yaml.sh
Labels: approved

#248 fix lookup-artifact-location and process-build-requests permission issues running on openshfit
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved

#249 create a new ci flow that is a subset of the kustomize dev flow
  .gitignore
  deploy/openshift-ci.sh
  deploy/operator/overlays/ci-template/base-deployment.yaml
  deploy/operator/overlays/ci-template/kustomization.yaml
  deploy/operator/overlays/ci-template/operator-images.yaml
  deploy/overlays/ci-template/kustomization.yaml
  deploy/overlays/ci-template/system-config.yaml
Labels: approved, lgtm

#250 periodic not failing when initial pr fails
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved, lgtm

#230 Move in-repo tests to use container image based storage
  deploy/overlays/dev-template/config.yaml
  java-components/sidecar/pom.xml
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/DeployResource.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/DockerAuthEntry.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/containerregistry/DockerConfig.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/s3/S3Deployer.java
  openshift-with-appstudio-test/e2e/util.go
  pkg/reconciler/configmap/configmap.go
Labels: approved, lgtm

#256 Handle no build tool correctly
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: lgtm

#260 Handle deployment in the cache
  config/kcp/apiexport_jvmbuildservice.yaml
  config/kcp/apiresourceschema_jvmbuildservice.yaml
  deploy/base-development.sh
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  deploy/crds/base/jvmbuildservice.io_rebuiltartifacts.yaml
  deploy/crds/base/kustomization.yaml
  deploy/operator/base/rbac.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/BuildInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/cache/pom.xml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/artifactwatch/RebuiltArtifacts.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/DeployData.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/Deployer.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/DeployerUtil.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/Gav.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/containerregistry/DockerAuthEntry.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/containerregistry/DockerConfig.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/deploy/s3/S3Deployer.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/DeployResource.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/util/FileUtil.java
  java-components/cache/src/main/resources/application.properties
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/ContainerRegistryDeployerTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/ContainerRegistryDeployerTestResource.java
  java-components/dependency-analyser/src/main/java/com/redhat/hacbs/container/analyser/RebuildService.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/Contaminant.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildStatus.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/RebuiltArtifact.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/RebuiltArtifactSpec.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/util/HashUtil.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/util/ResourceNameUtils.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/DeployResource.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/MavenProxyResource.java
  java-components/sidecar/src/main/java/com/redhat/hacbs/sidecar/resources/deploy/s3/S3Deployer.java
  java-components/sidecar/src/test/java/com/redhat/hacbs/sidecar/resources/deploy/DeployResourceTest.java
  openshift-with-appstudio-test/e2e/util.go
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/apis/jvmbuildservice/v1alpha1/rebuiltartifact_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_rebuiltartifact.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/rebuiltartifact.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/interface.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/rebuiltartifact.go
  pkg/client/listers/jvmbuildservice/v1alpha1/expansion_generated.go
  pkg/client/listers/jvmbuildservice/v1alpha1/rebuiltartifact.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/dependencybuild/scripts/deploy.sh
Labels: approved, lgtm

#262 Fix logic error in Java version detection
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/maven/JavaVersionDiscovery.java
Labels: lgtm

#265 Merge maven-metadata.xml versions
  deploy/base/config.yaml
  deploy/base/maven-v0.2.yaml
  hack/examples/pipeline.yaml
  hack/examples/run-jenkins.sh
  hack/examples/run-jenkins.yaml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/CacheMavenResource.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/CacheFacade.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryCache.java
  java-components/cache/src/main/resources/application.properties
Labels: lgtm

#269 PLNSRVCE-658: switch from per user ns cfgmap to userconfig crd
  deploy/base/config.yaml
  deploy/crds/base/jvmbuildservice.io_userconfigs.yaml
  deploy/crds/base/kustomization.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  deploy/operator/base/rbac.yaml
  deploy/overlays/dev-template/config.yaml
  openshift-with-appstudio-test/e2e/util.go
  pkg/apis/jvmbuildservice/v1alpha1/register.go
  pkg/apis/jvmbuildservice/v1alpha1/systemconfig_types.go
  pkg/apis/jvmbuildservice/v1alpha1/userconfig_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/fake/fake_userconfig.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/jvmbuildservice_client.go
  pkg/client/clientset/versioned/typed/jvmbuildservice/v1alpha1/userconfig.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/interface.go
  pkg/client/informers/externalversions/jvmbuildservice/v1alpha1/userconfig.go
  pkg/client/listers/jvmbuildservice/v1alpha1/expansion_generated.go
  pkg/client/listers/jvmbuildservice/v1alpha1/userconfig.go
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/configmap/configmap.go
  pkg/reconciler/configmap/configmap_test.go
  pkg/reconciler/configmap/controller.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/userconfig/controller.go
  pkg/reconciler/userconfig/userconfig.go
  pkg/reconciler/userconfig/userconfig_test.go
  test/e2e/task_run_controller_test.go
Labels: approved

#271 Remove localstack support
  deploy/base-development.sh
  deploy/crds/base/jvmbuildservice.io_userconfigs.yaml
  deploy/kcp/apiexport_jvmbuildservice.yaml
  deploy/kcp/apiresourceschema_jvmbuildservice.yaml
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/util.go
  pkg/apis/jvmbuildservice/v1alpha1/userconfig_types.go
  pkg/reconciler/userconfig/userconfig.go
Labels: approved, lgtm

#276 return systemconfig definition to patch merge with jvm-build-service-builder-images
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
Labels: approved

#278 Fix potential NPE
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/CacheMavenResource.java
Labels: approved, lgtm
