Repository redhat-appstudio/jvm-build-service, pull requests merged in 2023-03, with the labels that each got.

#513 STONEBLD-844 Strip bytecode markers from untrusted repos
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/DeployCommand.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RemoteRepositoryManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryCache.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/LocalCacheTest.java
  java-components/classfile-tracker/src/main/java/com/redhat/hacbs/classfile/tracker/ClassFileTracker.java
  java-components/classfile-tracker/src/main/java/com/redhat/hacbs/classfile/tracker/ClassTrackingWriteDataVisitor.java
  java-components/classfile-tracker/src/test/java/com/redhat/hacbs/classfile/tracker/ClassTrackingModificationTestCase.java
Labels: approved

#514 STONEBLD-726 Initial CLI for JVM Build Service
  .tekton/cli-pull-request.yaml
  .tekton/cli-push.yaml
  java-components/cli/pom.xml
  java-components/cli/src/main/docker/Dockerfile.all-in-one
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/CustomFactory.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/InteractiveParameterConsumer.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/Main.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/MainCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/QuitCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/RequestScopedCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactBuildCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactListCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactLogsCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactRebuildCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactSummaryCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/GavCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildListCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildLogsCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildSummaryCommand.java
  java-components/cli/src/main/resources/application.properties
  java-components/pom.xml
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/ArtifactBuild.java
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#518 Add option to allow Ivy Repo
  java-components/build-request-processor/src/main/resources/gradle/repositories.gradle
Labels: approved

#519 Fix incorrect repo in dockerfile
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved

#517 STONEBLD-868 Include PipelineRun yaml in report
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  openshift-with-appstudio-test/e2e/periodic_test.go
  openshift-with-appstudio-test/e2e/util.go
  openshift-with-appstudio-test/main/generatereport.go
Labels: approved

#520 Minor CLI fix
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactSummaryCommand.java
Labels: approved

#522 STONEBLD-879 Update builder images
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
Labels: approved

#523 Update format plugins
  java-components/pom.xml
Labels: approved

#524 Add message to list artifacts command
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactListCommand.java
Labels: approved

#525 Don't fail the build if ant can't load
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/ant/AntUtils.java
Labels: approved

#521 STONEBLD-881 Add command to resolve missing artifacts
  java-components/cli/pom.xml
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactFixMissingCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/MissingArtifactBuildCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/MissingGavCompleter.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/util/GithubCredentials.java
Labels: approved

#526 STONEBLD-883 Enhance CLI commands
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/AddBuildRecipeRequest.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfoManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeDirectory.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeGroupManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeLayoutManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmInfoManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/util/FileUtil.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/DeployCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/build/AbstractPreprocessorTestCase.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactFixMissingCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildFixCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/repo/PullRequestCreator.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/repo/RepositoryChange.java
Labels: approved

#516 STONEBLD-892 remove pending pipelinerun related code; leverage k8s resource quota in e2e; sandbox quotas in stonesoup
  deploy/crds/base/jvmbuildservice.io_systemconfigs.yaml
  openshift-with-appstudio-test/e2e/periodic_test.go
  pkg/apis/jvmbuildservice/v1alpha1/systemconfig_types.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/controller.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/clusterresourcequota/controller.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  pkg/reconciler/k8sresourcequota/controller.go
  pkg/reconciler/k8sresourcequota/k8sresourcequota.go
  pkg/reconciler/pendingpipelinerun/controller.go
  pkg/reconciler/pendingpipelinerun/pending.go
  pkg/reconciler/pendingpipelinerun/pending_test.go
  pkg/reconciler/pendingpipelinerun/util.go
  pkg/reconciler/systemconfig/systemconfig.go
  pkg/reconciler/systemconfig/systemconfig_test.go
  test/e2e/suite_test.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/fake/doc.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/fake/fake_appliedclusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/fake/fake_clusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/clientset/versioned/typed/quota/v1/fake/fake_quota_client.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/quota/interface.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/quota/v1/clusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/informers/externalversions/quota/v1/interface.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/appliedclusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/clusterresourcequota.go
  vendor/github.com/openshift/client-go/quota/listers/quota/v1/expansion_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#515 STONEBLD-847 Use TLS to access the Cache
  hack/examples/pipeline-gradle.yaml
  java-components/build-request-processor/src/main/docker/Dockerfile.all-in-one
  java-components/build-request-processor/src/main/resources/application.properties
  pkg/apis/jvmbuildservice/v1alpha1/jbsconfig_types.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/artifactbuild/artifactbuild_test.go
  pkg/reconciler/artifactbuild/scripts/keystore.sh
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/jbsconfig/jbsconfig.go
Labels: approved

#527 Run CLI as root user to read kubeconfig
  java-components/cli/src/main/docker/Dockerfile.all-in-one
Labels: approved

#529 STONEBLD-903 Fix task validation issue
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/location/LookupScmLocationCommand.java
Labels: approved

#528 STONEBLD-877: Add ability to install RPM packages
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/AdditionalDownload.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/scripts/install-package.sh
Labels: approved, lgtm

#532 Add docs around CLI and improve usability
  docs/users.adoc
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/Main.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/QuitCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactFixMissingCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactListCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactLogsCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactRebuildCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactSummaryCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildFixCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildListCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildLogsCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/builds/BuildSummaryCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/repo/RepositoryChange.java
Labels: approved

#533 Minor CLI fixes
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactListCommand.java
  java-components/cli/src/main/java/io/github/redhatappstudio/jvmbuild/cli/artifacts/ArtifactRebuildCommand.java
Labels: approved

#534 Do not exit due to microdnf return code
  pkg/reconciler/dependencybuild/scripts/install-package.sh
Labels: approved, lgtm

#475 STONEBLD-42 Tighen up permissions
  deploy/operator/base/rbac.yaml
  pkg/controller/controller.go
  pkg/reconciler/jbsconfig/jbsconfig.go
Labels: approved

#535 Add support for Gradle 8.0
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtils.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/gradle/GradleUtilsTest.java
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/pipeline_run_controller_test.go
Labels: approved

#538 Update builder images
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
Labels: approved

#541 Fix typo
  java-components/classfile-tracker/src/main/java/com/redhat/hacbs/classfile/tracker/ClassFileTracker.java
Labels: approved

#537 STONEBLD-955 Make sure Red Hat repo is always configured
  pkg/reconciler/jbsconfig/jbsconfig.go
  pkg/reconciler/jbsconfig/jbsconfig_test.go
Labels: approved

#536 Add script to run JVM build service build
  hack/examples/run-jvm-build-service.sh
  hack/examples/run-jvm-build-service.yaml
Labels: approved

#542 STONEBLD-857 Fix Kaml build
  java-components/build-request-processor/src/main/resources/gradle/kotlinjs.gradle
Labels: approved

#548 GitScmLocator option to open local recipe repos w/o cloning them
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeRepositoryManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/GitScmLocator.java
Labels: lgtm, needs-ok-to-test

#480 Service Registry 2.4.1.Final
  hack/examples/run-service-registry.yaml
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#555 Skip running cobertura
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
Labels: ok-to-test

#554 Improve logging
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
  pkg/reconciler/dependencybuild/scripts/maven-build.sh
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: ok-to-test

#561 Only add .withAllowInsecureProtocol for SBT after 1.3.0
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: ok-to-test

#572 Add more logging. Add ability to use a specific branch for the recipe…
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeGroupManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeLayoutManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeRepositoryManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/GitScmLocator.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RemoteRepositoryManager.java
Labels: needs-ok-to-test

#577 Remove colors and correct cross-build command
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
Labels: ok-to-test
