Repository redhat-appstudio/jvm-build-service, pull requests merged in 2023-02, with the labels that each got.

#442 Use Github group ID
  java-components/adhoc-analyser-tool/pom.xml
  java-components/build-recipes-database/pom.xml
  java-components/build-request-processor/pom.xml
  java-components/cache/pom.xml
  java-components/classfile-tracker/pom.xml
  java-components/pom.xml
  java-components/resource-model/pom.xml
Labels: approved

#441 Legacy repos fix
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/location/LookupScmLocationCommand.java
Labels: approved

#444 Add release info to pom.xml
  java-components/pom.xml
Labels: approved

#445 Initial release
  java-components/adhoc-analyser-tool/pom.xml
  java-components/build-recipes-database/pom.xml
  java-components/build-request-processor/pom.xml
  java-components/cache/pom.xml
  java-components/classfile-tracker/pom.xml
  java-components/pom.xml
  java-components/resource-model/pom.xml
  release.sh
Labels: approved

#446 Fix release
  java-components/adhoc-analyser-tool/pom.xml
  java-components/build-recipes-database/pom.xml
  java-components/build-request-processor/pom.xml
  java-components/cache/pom.xml
  java-components/classfile-tracker/pom.xml
  java-components/pom.xml
  java-components/resource-model/pom.xml
  release.sh
Labels: approved

#447 Javadoc
  java-components/pom.xml
Labels: approved

#449 Remove legacy cache resource
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/LegacyCacheMavenResource.java
Labels: approved

#451 Ignore unkown properties
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/RepositoryInfo.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmInfo.java
Labels: approved

#454 Fix gosec complaint
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#455 Drop pod limits
  openshift-with-appstudio-test/e2e/periodic_test.go
Labels: approved

#450 STONEBLD-49 Split rebuild and user repo config
  deploy/base/gradle-v0.1.yaml
  deploy/base/maven-v0.2.yaml
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeDirectory.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeLayoutManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeRepositoryManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/mavenrepo/MavenRepositoryInfo.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/mavenrepo/MavenRepositoryInfoManager.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/BuildInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/resources/gradle/repositories.gradle
  java-components/cache/pom.xml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/V1CacheMavenResource.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/V2CacheMavenResource.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicy.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/CacheFacade.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RemoteRepositoryManager.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RepositoryCache.java
  java-components/cache/src/main/resources/application.properties
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/BuildPolicyManagerConfigTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/LocalCacheTest.java
  java-components/cache/src/test/java/com/redhat/hacbs/artifactcache/services/RelocationResourceTestCase.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
Labels: approved

#459 Use out rather than err
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/health/ThreadPoolHealthCheck.java
Labels: approved

#457 STONEBLD-58 Update builder images
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
Labels: approved

#456 STONEBLD-680 Add sbom merge to analyser
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/dependencies/AnalyserBase.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/dependencies/SBomGenerator.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/sbom/SBomMergeTestCase.java
  java-components/build-request-processor/src/test/resources/syft-sbom.json
Labels: approved

#462 Fix issue with cache URL
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/V2CacheMavenResource.java
Labels: approved

#461 Allow java version to be specified
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
Labels: approved

#463 STONEBLD-40 Add Grafana Dashboard
  deploy/monitoring/grafana-dashboards/grafana-dashboard-jvm-dependency-builds.json
  deploy/monitoring/grafana-dashboards/kustomization.yaml
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved

#464 Reduce log noise
  deploy/operator/base/deployment.yaml
Labels: approved

#465 Fix cache NPE
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/resources/V2CacheMavenResource.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/CacheFacade.java
Labels: approved

#458 Use the git hash for checkout
  deploy/crds/base/jvmbuildservice.io_artifactbuilds.yaml
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/location/LookupScmLocationCommand.java
  pkg/apis/jvmbuildservice/v1alpha1/common_types.go
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
Labels: approved

#469 Remove uneeded utility
  cmd/deletechainsfinalizer/main.go
Labels: approved

#468 Fix log timestamps
  cmd/controller/main.go
  go.mod
Labels: approved

#467 Add Ant support
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
  java-components/build-request-processor/pom.xml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/EntryPoint.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/BuildInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/ant/AntUtils.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/ant/IvyUtils.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/ant/AntPrepareCommand.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/ant/AntUtilsTest.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/ant/IvyUtilsTest.java
  java-components/build-request-processor/src/test/resources/com/redhat/hacbs/container/analyser/build/ant/build.xml
  java-components/build-request-processor/src/test/resources/com/redhat/hacbs/container/analyser/build/ant/ivysettings.xml
  java-components/pom.xml
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/ant-settings.sh
Labels: approved

#470 Increase timeout
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#466 Try multiple tools if there are multiple build files present
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  pkg/reconciler/artifactbuild/artifactbuild.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/dependencybuild_test.go
  test/e2e/pipeline_run_controller_test.go
Labels: approved

#476 Cut down number of repos in default config
  deploy/base/config.yaml
  openshift-with-appstudio-test/e2e/util.go
Labels: approved

#474 Fix locating Ant build files and Ant/Java version detection
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/ant/AntUtils.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/ant/AntUtilsTest.java
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/ant-settings.sh
Labels: approved

#477 Remove tar.gz file from deployment
  deploy/base/gradle-v0.1.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/ContainerDeployCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/DeployCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/DeployData.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/Deployer.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/S3DeployCommand.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/containerregistry/ContainerRegistryDeployer.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/s3/S3Deployer.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/deploy/ContainerRegistryDeployerTest.java
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-settings.sh
  pkg/reconciler/dependencybuild/scripts/maven-build.sh
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: approved

#478 Add commitHash
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/ScmInfo.java
Labels: needs-ok-to-test

#481 Don't set -Xmx when doing local development
  java-components/cache/src/main/resources/application.properties
Labels: approved

#479 Provide the SCM locator API as a Java library
  java-components/build-recipes-database/pom.xml
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/location/RecipeLayoutManager.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocator.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocatorConfig.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/TagInfo.java
  java-components/build-request-processor/pom.xml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/location/LookupScmLocationCommand.java
Labels: ok-to-test

#487 Add cacheRepoTags option for the ScmLocator to enable repo tag and hash caching between calls
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocator.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocatorConfig.java
Labels: approved, lgtm, needs-ok-to-test

#485 Add reproducer dockerfiles to DependencyBuild
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/RemoteRepositoryManager.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/DependencyBuildStatus.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/apis/jvmbuildservice/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
  pkg/reconciler/dependencybuild/scripts/maven-build.sh
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: approved

#482 Make build scripts verbose
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-settings.sh
  pkg/reconciler/dependencybuild/scripts/install-package.sh
  pkg/reconciler/dependencybuild/scripts/maven-build.sh
  pkg/reconciler/dependencybuild/scripts/maven-settings.sh
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: approved

#483 Fix cache clear issue
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/artifactwatch/CacheControl.java
Labels: approved

#486 Update builder images
  deploy/operator/config/kustomization.yaml
  deploy/operator/config/system-config.yaml
Labels: approved

#488 Fixes around dockerfiles
  openshift-with-appstudio-test/e2e/util.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved

#489 Submodules fix
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved

#491 Add empty mavenCentral(Username|Password) properties
  pkg/reconciler/dependencybuild/scripts/gradle-settings.sh
Labels: approved

#492 Add post build script support
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/BuildInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/model/v1alpha1/BuildRecipe.java
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
  pkg/reconciler/dependencybuild/scripts/maven-build.sh
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: approved

#493 Use Maven settings for Ant settings
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved

#484 Always resolve contamination
  pkg/reconciler/artifactbuild/artifactbuild.go
Labels: approved

#460 Attempt to handle cache problems
  deploy/crds/base/jvmbuildservice.io_dependencybuilds.yaml
  pkg/apis/jvmbuildservice/v1alpha1/dependencybuild_types.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: approved

#494 Retry requests on network issue
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/maven/MavenClient.java
Labels: approved

#496 Drain connections before closing
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/services/client/maven/MavenClient.java
Labels: approved

#502 Add ignore-not-found
  deploy/base-development.sh
Labels: approved

#504 Revert "Fix contamination handling logic"
  pkg/reconciler/artifactbuild/artifactbuild.go
Labels: approved

#505 STONEBLD-752 Add SCM info to rebuilt artifacts
  deploy/base/maven-v0.2.yaml
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/dependencies/SBomGenerator.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/deploy/DeployCommand.java
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/deploy/ContainerRegistryDeployerTest.java
  java-components/cache/src/main/java/com/redhat/hacbs/artifactcache/artifactwatch/RebuiltArtifacts.java
  java-components/cache/src/main/resources/application.properties
  java-components/classfile-tracker/src/main/java/com/redhat/hacbs/classfile/tracker/TrackingData.java
  java-components/classfile-tracker/src/test/java/com/redhat/hacbs/classfile/tracker/ClassTrackingModificationTestCase.java
  java-components/resource-model/src/main/java/com/redhat/hacbs/resources/util/HashUtil.java
  openshift-with-appstudio-test/e2e/jvm_build_service_test.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
Labels: approved

#508 STONEBLD-777 - tekton-ci: update bundle
  .tekton/build-request-processor-pull-request.yaml
  .tekton/build-request-processor-push.yaml
  .tekton/cache-pull-request.yaml
  .tekton/cache-push.yaml
  .tekton/controller-pull-request.yaml
  .tekton/controller-push.yaml
Labels: approved

#507 ScmLocator: allow plugging in a fallback ScmLocator
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/GitScmLocator.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/PomScmLocator.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocator.java
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/scm/ScmLocatorConfig.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/location/LookupScmLocationCommand.java
Labels: ok-to-test

#506 Update Ant Ivy default resolver
  java-components/build-request-processor/src/test/java/com/redhat/hacbs/container/analyser/build/ant/IvyUtilsTest.java
  java-components/build-request-processor/src/test/resources/com/redhat/hacbs/container/analyser/build/ant/ivysettings.xml
  pkg/reconciler/dependencybuild/scripts/ant-build.sh
Labels: approved, lgtm

#511 STONEBLD-693 Ability to test Java Artifacts
  java-components/build-recipes-database/src/main/java/com/redhat/hacbs/recipies/build/BuildRecipeInfo.java
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/analyser/build/LookupBuildInfoCommand.java
  pkg/reconciler/dependencybuild/scripts/gradle-build.sh
Labels: approved

#512 STONEBLD-56 Disable kotlin JS by default
  java-components/build-request-processor/src/main/java/com/redhat/hacbs/container/build/preprocessor/gradle/GradlePrepareCommand.java
  java-components/build-request-processor/src/main/resources/gradle/kotlinjs.gradle
Labels: approved

#500 Fix SBT MavenRepo URL
  pkg/reconciler/dependencybuild/scripts/sbt-build.sh
Labels: approved

#495 Update grafana dashboards on push
  .tekton/controller-push.yaml
Labels: approved
