Repository redhat-appstudio/jvm-build-service, pull requests merged in 2025-01, with the labels that each got.

#2335 Add domain proxy params
  deploy/pipeline/mw-pipeline-v0.1.yaml
Labels: lgtm

#2337 Sync buildah-oci-ta to be based upon 0.3
  deploy/tasks/README.md
  deploy/tasks/buildah-oci-ta.yaml
  pkg/apis/jvmbuildservice/v1alpha1/systemconfig_types.go
Labels: lgtm, ok-to-test

#2340 Upload build log to Bifrost
  deploy/pipeline/mw-pipeline-v0.1.yaml
  deploy/tasks/push-results.yaml
  pkg/apis/jvmbuildservice/v1alpha1/systemconfig_types.go
  pkg/reconciler/dependencybuild/buildrecipeyaml.go
  pkg/reconciler/dependencybuild/dependencybuild.go
Labels: ok-to-test
